#!/bin/bash


# Usage:
#   bartermapp [arg1] [arg2]
#      arg1: terminal program to run
#      arg2: number of times do apply additional 
#            x offset defined by xinterval

# Dependencies:
#   tdrop


xoffset=0
xinterval=60
yoffset=440
width=600
height=600
terminal=st


x=$(expr $xoffset + $xinterval \* $2 - $xinterval)

tdrop -a -w $width -h $height -x $x -y $yoffset -n "$1 $2" -f "-e bash -c 'bspc node -g sticky && $1'" $terminal
