#! /bin/sh

xresource() {
    # 1. query xrdb for all settings
    # 2. use grep to find the one we want
    # 3. use sed to get only the value
    # 4. get the last value if there's multiple
    xrdb -query | grep -E "^(bspwm|\*)\.$1:" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

sxhkd &


bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#e91e63"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       'button1'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a w3m state=floating follow=off
bspc rule -a feh state=floating rectangle=1200x900+320+100

polybar example &
feh --bg-fill ~/Pictures/vapor2.jpg &
redshift-gtk &
sleep .5
urxvt -e ranger &
sleep .5

bspc node -p east
bspc node -o 0.58
urxvt -e htop &
sleep .5
bspc node -p south
bspc node -o 0.13


urxvt -e calcurse &
sleep .5

bspc node -p south
urxvt -e bash -c "neofetch && bash" &




