#! /bin/sh

sxhkd &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#e72d6a"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       'button1'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


polybar example &
feh --bg-fill ~/Pictures/stag-sunset.jpg &
redshift-gtk &
urxvt -e ranger &
sleep .5

bspc node -p east
bspc node -o 0.58
urxvt -e htop &
sleep .5
bspc node -p south
bspc node -o 0.13


urxvt -e cava &
sleep .5

bspc node -p south
bspc node -o 0.2
urxvt -e bash -c "neofetch && bash" &
bspc rule -a chromium-browser -o desktop='^2'




