#! /bin/sh

sxhkd &
wal -R

bspc monitor -d I II III IV

bspc config border_width         0
bspc config window_gap          50


BORDERCOLOR=`xrdb -query | grep '*.color4' | awk '{print $NF}'`
bspc config focused_border_color $BORDERCOLOR
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       'button1'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a w3m state=floating follow=off
bspc rule -a feh state=floating rectangle=1200x900+320+100

# bar at top of screen
polybar example &
compton &
sleep 1


# set redshift location (shifts screen color to red when sun is down)
redshift-gtk -l 43.6532:-79.3832 &
sleep .5

# ---window layout on login---

# file browser
urxvt -e ranger &
sleep .5
bspc node -p east
bspc node -o 0.58

# process/task manager
urxvt -e htop &
sleep .5
bspc node -p south
bspc node -o 0.13

# Calendar
urxvt -e calcurse &
sleep .5

bspc node -p south

# empty terminal, displays system info on startup
urxvt -e bash -c "neofetch && bash" &

# start music player service
mpd &




